name: openapi2postman
description: "GitHub action to push openapi (OpenAPI 3.0, 3.1 and Swagger 2.0) file to Postman directly from your workflow"
inputs:
  api-key:
    description: "Your Postman API key"
    required: true
  workspace-id:
    description: "The Postman workspace ID"
    required: true
  collection-id:
    description: "The Postman collection ID"
    required: true
  file:
    description: "OpenAPI JSON file"
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - "-api-key=${{ inputs.api-key }}"
    - "-workspace-id=${{ inputs.workspace-id }}"
    - "-collection-id=${{ inputs.collection-id }}"
    - "-file=${{ inputs.file }}"
branding:
  icon: arrow-up
  color: orange
